import os

folders = {
    "equus-quagga": "Plains Zebra",
    "panthera-leo": "Lion",
    "panthera-onca": "Jaguar",
    "ursus-arctos-horribilis": "Grizzly Bear",
    "megaptera-novaeangliae": "Humpback Whale",
    "panthera-tigris": "Tiger",
    "haliaeetus-leucocephalus": "Bald Eagle",
    "tyrannosaurus-rex": "T. Rex",
    "diplodocus": "Diplodocus",
    "panthera-pardus": "Leopard",
    "homo-sapiens": "Modern Humans",
    "phoebetria-fusca": "Sooty Albatross",
    "bos-taurus": "Domestic Cow",
    "gallus-gallus-domesticus": "Chicken",
    "ovis-aries": "Sheep",
    "ceratotherium-simum": "White Rhino",
    "loxodonta-africana": "African Bush Elephant",
    "tursiops-truncatus": "Common Bottlenose Dolphin",
    "orcinus-orca": "Killer Whale",
    "carcharodon-carcharias": "Great White Shark",
    "canis-lupus-familiaris": "Domestic Dog",
    "felis-catus": "Cat",
    "salmo-salar": "Salmon",
    "balaenoptera-musculus": "Blue Whale",
    "giraffa-camelopardalis": "Northern Giraffe",
    "ophiophagus-hannah": "King Cobra",
    "crotalus-atrox": "Western diamondback rattlesnake",
    "varanus-komodoensis": "Komodo Dragon",
    "pterois-mombasae": "African Lionfish",
    "spinosaurus-aegyptiacus": "Spinosaurus",
    "crocodylus-niloticus": "Crocodile",
    "falco-peregrinus": "Peregrine Falcon",
    "gorilla-gorilla": "Gorilla",
    "pongo-abelii": "Orangutan",
    "gavialis-gangeticus": "Gharial",
    "acinonyx-jubatus": "Cheetah",
    "canis-lupus": "Wolf",
    "ursus-maritimus": "Polar Bear",
    "hippopotamus-amphibius": "Hippopotamus",
    "iguana-iguana": "Green Iguana",
    "iguanodon-bernissartensis": "Iguanadon",
    "stegosaurus-stenops": "Stegosaurus",
    "triceratops-horridus": "Triceratops",
    "pteranodon-longiceps": "Pteranodon",
    "ankylosaurus-magniventris": "Ankylosaurus",
    "agalychnis-callidryas": "Tree Frog",
    "dendrobatidae": "Poison Dart Frog",
    "mellisuga-helenae": "Bee Hummingbird",
    "eudocimus-albus": "American white ibis",
    "sphyrna-mokarran": "Great hammerhead shark",
    "trilobita": "Trilobites",
    "enteroctopus-dofleini": "Giant Pacific octopus",
    "coelacanthiformes": "Coelacanth",
    "equus-caballus": "Horse",
    "odobenus-rosmarus": "Walrus",
    "physeter-macrocephalus": "Sperm Whale",
    "dugong-dugon": "Dugong",
    "eunectes-murinus": "Green Anaconda",
    "malayopython-reticulatus": "Reticulated Python",
    "rattus-rattus": "Black Rat",
    "ornithorhynchus-anatinus": "Platypus",
    "desmodus-rotundus": "Vampire Bat",
    "taurotragus-oryx": "Common Eland",
    "connochaetes-gnou": "Wildebeest",
    "puma-concolor": "Cougar",
    "formicidae": "Ant",
    "danaus-plexippus": "Monarch Butterfly",
    "papilio-glaucus": "Eastern Tiger Swallowtail",
    "heterocera": "Moth",
    "dermochelys-coriacea": "Leatherback Sea Turtle",
    "lampropeltis-triangulum": "Milk snake",
    "heloderma-suspectum": "Gila Monster",
    "macropus-giganteus": "Kangaroo",
    "ailuropoda-melanoleuca": "Giant Panda",
    "ailurus-fulgens": "Red Panda",
    "procyon-lotor": "Raccoon",
    "smilodon-populator": "Smilodon",
    "mammuthus-primigeniu": "Woolly Mammoth",
    "tapirus": "Tapir",
    "bison-bison": "American Bison",
    "alces-alces": "Moose",
    "aptenodytes-forsteri": "Emperor Penguin",
    "hydrurga-leptonyx": "Leopard Seal",
    "bradypus-variegatus": "Brown-throated Three-toed Sloth",
    "sciurus-carolinensis": "Eastern Gray Squirrel",
    "cyanocitta-cristata": "Blue Jay",
    "periplaneta-americana": "American Cockroach",
    "anas-platyrhynchos": "Mallard",
    "pavo-cristatus": "Indian Peafowl",
    "ara-macao": "Scarlet Macaw",
    "enhydra-lutris": "Sea Otter",
    "physalia-physalis": "Portuguese Man o' War",
    "codium-fragile": "Dead Man's Fingers",
    "centruroides-vittatus": "Striped Bark Scorpion",
    "lemur-catta": "Ring-tailed Lemur",
    "delphinapterus-leucas": "Beluga",
    "inia-geoffrensis": "Boto",
    "phascolarctos-cinereus": "Koala",
    "spheniscus-demersus": "African Penguin",
    "aquila-chrysaetos": "Golden Eagle",
    "branta-canadensis": "Canada Goose",
    "turdus-migratorius": "American Robin",
    "passerina-ciris": "Painted Bunting",
    "geococcyx-californianus": "Greater Road"
}


root_path = "dataset"

for old_name, new_name in folders.items():
    old_path = os.path.join(root_path, old_name)
    new_path = os.path.join(root_path, new_name)
    os.rename(old_path, new_path)
    print(f"Переименовано: '{old_name}' -> '{new_name}'")
